[project]
name = "redirector"
version = "1.1.0"
description = ""
authors = [{ name = "Derk Weijers", email = "derk@weijers.xyz" }]
requires-python = ">=3.10,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "fastapi[all]>=0.141.1,<1",
    "boto3>=1.24.5,<2",
]

[dependency-groups]
dev = [
    "pytest>=9,<10",
    "ruff>=0.16.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = ["FAST", "I", "PL", "UP", "E", "W"]