name: Publish Docker image
on:
  push:
    branches: [ 'github_actions' ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Check out the repo
        uses: actions/checkout@v2

      - run: ls

      - name: Export requirements.txt
        run: poetry export -f requirements.txt -o requirements.txt

      - run: ls

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/orbiterforum/redirector:latest