name: Publish Docker image
on:
  push:
    branches: [ 'main' ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Export requirements.txt
        run: poetry export -f requirements.txt -o requirements.txt

      - name: Get project version
        id: project_version
        run: echo "::set-output name=version::$(poetry version -s)"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/orbiterforum/redirector:latest
            ghcr.io/orbiterforum/redirector:${{steps.project_version.outputs.version}}

      - name: Commit requirements.txt for future use
        uses: EndBug/add-and-commit@v9
        with:
          add: requirements.txt
          message: Generated new requirements.txt
